### ISSUE TITLE
`alejandra` `exclude` option creates call error.

### ISSUE THREAD

**Issue by MathiasRudolphSec** [cachix/git-hooks.nix#490]
I have alejandra configured with

```nix
let
  sources = import ./sources.nix;
  nix-pre-commit-hooks = import sources."pre-commit-hooks.nix";
in {
  pre-commit-check = nix-pre-commit-hooks.run {
    src = ./.;
    excludes = ["sources\\.json"];
    hooks = {
      alejandra.enable = true;
      alejandra.settings.exclude = ["nix/sources.nix"];
    };
  };
}
```

`nix-build` on this derivation produces the following error:
```shell
Running: $ pre-commit run --all-files
alejandra................................................................Failed
- hook id: alejandra
- exit code: 2

error: Found argument '--exclude 'nix/sources.nix'' which wasn't expected, or isn't valid in this context

        If you tried to supply `--exclude 'nix/sources.nix'` as a value rather than a flag, use `-- --exclude 'nix/sources.nix'`

USAGE:
    alejandra [OPTIONS] [INCLUDE]...

For more information try --help
error: Found argument '--exclude 'nix/sources.nix'' which wasn't expected, or isn't valid in this context

        If you tried to supply `--exclude 'nix/sources.nix'` as a value rather than a flag, use `-- --exclude 'nix/sources.nix'`

USAGE:
    alejandra [OPTIONS] [INCLUDE]...

For more information try --help
```

I find the `.pre-commit-config.yaml` a bit strange:
```yaml
"hooks": [
        {
          "always_run": false,
          "args": [],
          "entry": "/nix/store/6580jj75y8fqx5ik1d5q8g8kjsck78c4-alejandra-3.0.0/bin/alejandra '--exclude '\\''nix/sources.nix'\\'''",
          "exclude": "^$",
          "exclude_types": [],
          "fail_fast": false,
          "files": "\\.nix$",
          "id": "alejandra",
          "language": "system",
          "name": "alejandra",
          "pass_filenames": true,
          "require_serial": false,
          "stages": [
            "commit"
          ],
          "types": [
            "file"
          ],
          "types_or": [],
          "verbose": false
        },
      ]
```
If `entry` reflects the call, the `exclude` argument is taken as a literal file name? Maybe?

Could there be a double shell escape in: https://github.com/cachix/git-hooks.nix/blob/master/modules/hooks.nix#L1724-L1742 ?
